### ISSUE TITLE
Exception 'Http\Client\Exception\RequestException' with message 'transfer closed with ... bytes remaining to read'

### ISSUE THREAD

**Issue by arogachev** [yiisoft-contrib/yiiframework.com#1013]
in `/vendor/php-http/curl-client/src/Client.php:137`

```
Stack trace:
#0 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(82): Http\Client\Curl\Client->sendRequest()
#1 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/Authentication.php(83): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#2 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Github\HttpClient\Plugin\Authentication->handleRequest()
#3 /var/www/yiiframework/vendor/php-http/client-common/src/Plugin/HeaderAppendPlugin.php(43): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#4 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HeaderAppendPlugin->handleRequest()
#5 /var/www/yiiframework/vendor/php-http/client-common/src/Plugin/HeaderDefaultsPlugin.php(41): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#6 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HeaderDefaultsPlugin->handleRequest()
#7 /var/www/yiiframework/vendor/php-http/client-common/src/Plugin/AddHostPlugin.php(64): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#8 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AddHostPlugin->handleRequest()
#9 /var/www/yiiframework/vendor/php-http/client-common/src/Plugin/RedirectPlugin.php(145): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#10 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\RedirectPlugin->handleRequest()
#11 /var/www/yiiframework/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php(39): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#12 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HistoryPlugin->handleRequest()
#13 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php(26): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#14 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(161): Github\HttpClient\Plugin\GithubExceptionThrower->handleRequest()
#15 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#16 /var/www/yiiframework/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}()
#17 /var/www/yiiframework/vendor/php-http/client-common/src/HttpMethodsClient.php(208): Http\Client\Common\PluginClient->sendRequest()
#18 /var/www/yiiframework/vendor/php-http/client-common/src/HttpMethodsClient.php(194): Http\Client\Common\HttpMethodsClient->sendRequest()
#19 /var/www/yiiframework/vendor/php-http/client-common/src/HttpMethodsClient.php(112): Http\Client\Common\HttpMethodsClient->send()
#20 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php(164): Http\Client\Common\HttpMethodsClient->post()
#21 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/Api/AcceptHeaderTrait.php(31): Github\Api\AbstractApi->postRaw()
#22 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php(146): Github\Api\GraphQL->postRaw()
#23 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/Api/AcceptHeaderTrait.php(26): Github\Api\AbstractApi->post()
#24 /var/www/yiiframework/vendor/knplabs/github-api/lib/Github/Api/GraphQL.php(34): Github\Api\GraphQL->post()
#25 /var/www/yiiframework/components/github/GithubRepoSet.php(113): Github\Api\GraphQL->execute()
#26 /var/www/yiiframework/components/github/GithubProgress.php(48): app\components\github\GithubRepoSet->getData()
#27 /var/www/yiiframework/commands/GithubProgressController.php(30): app\components\github\GithubProgress->getData()
#28 /var/www/yiiframework/commands/GithubProgressController.php(19): app\commands\GithubProgressController->fetchProgress()
#29 [internal function]: app\commands\GithubProgressController->actionIndex()
#30 /var/www/yiiframework/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#31 /var/www/yiiframework/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#32 /var/www/yiiframework/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction()
#33 /var/www/yiiframework/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#34 /var/www/yiiframework/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#35 /var/www/yiiframework/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#36 /var/www/yiiframework/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#37 /var/www/yiiframework/yii(27): yii\base\Application->run()
#38 {main}
```

**Comment by arogachev** [comment]
Can not reproduce it locally yet. Happens on rare occasions.
