### ISSUE TITLE
Can't generate 1.0 and 1.1 docs on PHP 7

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#197]
I'm using PHP 7.1.2 and I guess that's the problem. Either we should make another 1.1 release where it's fixed soon or fix it another way.

```php
$ ./yii guide 1.0
Start generating guide 1.0 in Deutsch...
Exception 'Error' with message '[] operator not supported for strings'

in C:\dev\yiiframework.com\data\yii-1.1\framework\vendors\TextHighlighter\Text\Highlighter\Renderer\Array.php:153

Stack trace:
#0 C:\dev\yiiframework.com\data\yii-1.1\framework\vendors\TextHighlighter\Text\Highlighter.php(377): Text_Highlighter_Renderer_Array->acceptToken('inlinetags', '')
#1 C:\dev\yiiframework.com\apidoc\Yii1MarkdownParser.php(199): Text_Highlighter->highlight('return array(\n ...')
#2 C:\dev\yiiframework.com\apidoc\Yii1MarkdownParser.php(184): app\apidoc\Yii1MarkdownParser->highlightCodeBlock('return array(\n ...')
#3 [internal function]: app\apidoc\Yii1MarkdownParser->_doFencedCodeBlocks_callback(Array)
#4 C:\dev\yiiframework.com\data\yii-1.1\framework\vendors\markdown\markdown.php(2373): preg_replace_callback('{\r\n\t\t\t\t(?:\\n|\\A...', Array, 'Erstellen der e...')
#5 C:\dev\yiiframework.com\data\yii-1.1\framework\vendors\markdown\markdown.php(132): MarkdownExtra_Parser->doFencedCodeBlocks('Erstellen der e...')
#6 C:\dev\yiiframework.com\apidoc\Yii1GuideRenderer.php(151): Markdown_Parser->transform('Erstellen der e...')
#7 C:\dev\yiiframework.com\apidoc\Yii1GuideRenderer.php(111): app\apidoc\Yii1GuideRenderer->filterContent('Erstellen der e...')
#8 C:\dev\yiiframework.com\apidoc\Yii1GuideRenderer.php(88): app\apidoc\Yii1GuideRenderer->getContent('C:\\dev\\yiiframe...')
#9 C:\dev\yiiframework.com\apidoc\Yii1GuideRenderer.php(64): app\apidoc\Yii1GuideRenderer->renderTutorial()
#10 C:\dev\yiiframework.com\commands\GuideController.php(155): app\apidoc\Yii1GuideRenderer->renderGuide('1.0', 'de')
#11 [internal function]: app\commands\GuideController->actionGenerate('1.0')
#12 C:\dev\yiiframework.com\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#13 C:\dev\yiiframework.com\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#14 C:\dev\yiiframework.com\vendor\yiisoft\yii2\console\Controller.php(134): yii\base\Controller->runAction('', Array)
#15 C:\dev\yiiframework.com\vendor\yiisoft\yii2\base\Module.php(523): yii\console\Controller->runAction('', Array)
#16 C:\dev\yiiframework.com\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('guide', Array)
#17 C:\dev\yiiframework.com\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('guide', Array)
#18 C:\dev\yiiframework.com\vendor\yiisoft\yii2\base\Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 C:\dev\yiiframework.com\yii(27): yii\base\Application->run()
#20 {main}
```

**Comment by cebe** [comment]
works for me on 7.1.0, trying with 7.1.7 now.

**Comment by cebe** [comment]
are you sure you have the latest version of 1.1 checked out in data directory?

I do not see how output could ever be a string at this point: https://github.com/yiisoft/yii/blob/7944ca5c6f246b22a6c24bdc8ab3e0f6c9c7fcbc/framework/vendors/TextHighlighter/Text/Highlighter/Renderer/Array.php#L146

**Comment by samdark** [comment]
My bad. Was running `./yii` instead of `make`.

**Comment by samdark** [comment]
Still it fails

**Comment by samdark** [comment]
make fails for 1.1 by default. You need to get into `data/yii-1.1` dir and run `composer install` there once.

**Comment by cebe** [comment]
interesting, it should do that by itself, could be it does not work with the latest version of the repo, need to try it with a fresh install. https://github.com/yiisoft-contrib/yiiframework.com/blob/master/Makefile#L72
