### ISSUE TITLE
npm install and gulp are broken

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#300]
npm install does not work correctly, it prints error messages but exit code is 0 so we did not notice...

```
             stderr:
                  npm WARN prefer global node-gyp@3.2.1 should be installed with -g
                  WARN invalid config loglevel="notice"
                  Cannot download "https://github.com/sass/node-sass/releases/download/vhttps://registry.npmjs.org/node-sass/-/node-sass-3.4.2.tgz/linux-x64-46_binding.node": 
                  
                  HTTP error 404 Not Found
                  
                  Hint: If github.com is not accessible in your location
                        try setting a proxy via HTTP_PROXY, e.g. 
                  
                        export HTTP_PROXY=http://example.com:1234
                  
                  or configure npm proxy via
                  
                        npm config set proxy http://example.com:8080
                  gyp info it worked if it ends with ok
                  gyp verb cli [ '/usr/bin/nodejs',
                  gyp verb cli   '/var/www/yiiframework/node_modules/node-gyp/bin/node-gyp.js',
                  gyp verb cli   'rebuild',
                  gyp verb cli   '--verbose',
                  gyp verb cli   '--libsass_ext=',
                  gyp verb cli   '--libsass_cflags=',
                  gyp verb cli   '--libsass_ldflags=',
                  gyp verb cli   '--libsass_library=' ]
                  gyp info using node-gyp@https://registry.npmjs.org/node-gyp/-/node-gyp-3.2.1.tgz
                  gyp info using node@4.8.2 | linux | x64
                  gyp verb command rebuild []
                  gyp verb command clean []
                  gyp verb clean removing "build" directory
                  gyp verb command configure []
                  gyp verb check python checking for Python executable "python2" in the PATH
                  gyp verb `which` succeeded python2 /usr/bin/python2
                  gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
                  gyp verb get node dir no --target version specified, falling back to host node version: 4.8.2
                  gyp verb command install [ '4.8.2' ]
                  gyp verb install input version string "4.8.2"
                  gyp verb install installing version: 4.8.2
                  gyp verb install --ensure was passed, so won't reinstall if already installed
                  gyp verb install version is already installed, need to check "installVersion"
                  gyp verb got "installVersion" 9
                  gyp verb needs "installVersion" 9
                  gyp verb install version is good
                  gyp verb get node dir target node version installed: 4.8.2
                  gyp verb build dir attempting to create "build" dir: /var/www/yiiframework/node_modules/node-sass/build
                  gyp verb build dir "build" dir needed to be created? /var/www/yiiframework/node_modules/node-sass/build
                  gyp verb build/config.gypi creating config file
                  gyp verb build/config.gypi writing out config file: /var/www/yiiframework/node_modules/node-sass/build/config.gypi
                  gyp verb config.gypi checking for gypi file: /var/www/yiiframework/node_modules/node-sass/config.gypi
                  gyp verb common.gypi checking for gypi file: /var/www/yiiframework/node_modules/node-sass/common.gypi
                  gyp verb gyp gyp format was not specified; forcing "make"
                  gyp info spawn /usr/bin/python2
                  gyp info spawn args [ '/var/www/yiiframework/node_modules/node-gyp/gyp/gyp_main.py',
                  gyp info spawn args   'binding.gyp',
                  gyp info spawn args   '-f',
                  gyp info spawn args   'make',
                  gyp info spawn args   '-I',
                  gyp info spawn args   '/var/www/yiiframework/node_modules/node-sass/build/config.gypi',
                  gyp info spawn args   '-I',
                  gyp info spawn args   '/var/www/yiiframework/node_modules/node-gyp/addon.gypi',
                  gyp info spawn args   '-I',
                  gyp info spawn args   '/root/.node-gyp/4.8.2/include/node/common.gypi',
                  gyp info spawn args   '-Dlibrary=shared_library',
                  gyp info spawn args   '-Dvisibility=default',
                  gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.8.2',
                  gyp info spawn args   '-Dnode_gyp_dir=/var/www/yiiframework/node_modules/node-gyp',
                  gyp info spawn args   '-Dnode_lib_file=node.lib',
                  gyp info spawn args   '-Dmodule_root_dir=/var/www/yiiframework/node_modules/node-sass',
                  gyp info spawn args   '--depth=.',
                  gyp info spawn args   '--no-parallel',
                  gyp info spawn args   '--generator-output',
                  gyp info spawn args   'build',
                  gyp info spawn args   '-Goutput_dir=.' ]
                  gyp verb command build []
                  gyp verb build type Release
                  gyp verb architecture x64
                  gyp verb node dev dir /root/.node-gyp/4.8.2
                  gyp verb `which` succeeded for `make` /usr/bin/make
                  gyp info spawn make
                  gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
                  make: g++: Command not found
                  make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
                  gyp ERR! build error 
                  gyp ERR! stack Error: `make` failed with exit code: 2
                  gyp ERR! stack     at ChildProcess.onExit (/var/www/yiiframework/node_modules/node-gyp/lib/build.js:276:23)
                  gyp ERR! stack     at emitTwo (events.js:87:13)
                  gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
                  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
                  gyp ERR! System Linux 4.9.0-5-amd64
                  gyp ERR! command "/usr/bin/nodejs" "/var/www/yiiframework/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
                  gyp ERR! cwd /var/www/yiiframework/node_modules/node-sass
                  gyp ERR! node -v v4.8.2
                  gyp ERR! node-gyp -v vhttps://registry.npmjs.org/node-gyp/-/node-gyp-3.2.1.tgz
                  gyp ERR! not ok 
                  Build failed
                  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@https://registry.npmjs.org/node-sass/-/node-sass-3.4.2.tgz (node_modules/node-sass):
                  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@3.4.2 postinstall: `node scripts/build.js`
                  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
              stdout:
                  
                  > node-sass@3.4.2 install /var/www/yiiframework/node_modules/node-sass
                  > node scripts/install.js
                  
                  
                  > spawn-sync@1.0.13 postinstall /var/www/yiiframework/node_modules/spawn-sync
                  > node postinstall
                  
                  
                  > node-sass@3.4.2 postinstall /var/www/yiiframework/node_modules/node-sass
                  > node scripts/build.js
                  
                  Building: /usr/bin/nodejs /var/www/yiiframework/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
                  make: Entering directory '/var/www/yiiframework/node_modules/node-sass/build'
                    g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.2"' -I/root/.node-gyp/4.8.2/include/node -I/root/.node-gyp/4.8.2/src -I/root/.node-gyp/4.8.2/deps/uv/include -I/root/.node-gyp/4.8.2/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
                  src/libsass.target.mk:136: recipe for target 'Release/obj.target/libsass/src/libsass/src/ast.o' failed
                  make: Leaving directory '/var/www/yiiframework/node_modules/node-sass/build'
                  added 2 packages and updated 400 packages in 16.639s
```

same issue with gulp:

```
gulp build --production
                  [13:31:50] Unsupported gulp version
```

exit code: zero, because its all fine! :-D

**Comment by cebe** [comment]
https://github.com/npm/npm/issues/17875

**Comment by cebe** [comment]
managed to install yarn. added a yarn.lock file.

**Comment by cebe** [comment]
> update readme. yarn -> npm

it's of course npm -> yarn :)
