### ISSUE TITLE
Gulp task fails

### ISSUE THREAD

**Issue by machour** [yiisoft-contrib/yiiframework.com#413]
When running the command to generate contributors, the scripts ends with a gulp error:

```
🍺  ~/yii3/yiiframework.com (fix/php73-compat)$ ./yii contributors/generate
[23:15:49] 'styles' errored after 1.79 s
[23:15:49] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:144:11)
    at Object.utimes (fs.js:1113:14)
    at /Users/didou/yii3/yiiframework.com/node_modules/gulp-touch/index.js:11:13
    at wrappedMapper (/Users/didou/yii3/yiiframework.com/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/didou/yii3/yiiframework.com/node_modules/map-stream/index.js:96:21)
    at Pumpify.ondata (/Users/didou/yii3/yiiframework.com/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at Pumpify.emit (events.js:182:13)
    at Pumpify.EventEmitter.emit (domain.js:459:23)
    at addChunk (/Users/didou/yii3/yiiframework.com/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/didou/yii3/yiiframework.com/node_modules/readable-stream/lib/_stream_readable.js:278:11)
```

Gulp version:

```
🍺  ~/yii3/yiiframework.com (fix/php73-compat)$ gulp --version
[23:16:49] CLI version 2.0.1
[23:16:49] Local version 4.0.0-alpha.3
```

**Comment by cebe** [comment]
there is a yarn.lock file, so `yarn install` should give you the required versions as far as I see.

My env (which is working):

```
$ node --version
v4.8.2
$ yarn --version
1.5.1
$ gulp --version
[11:47:19] CLI version 2.0.1
[11:47:19] Local version 4.0.0-alpha.3
```

**Comment by machour** [comment]
Thank you, it's now working after downgrading from node 10 to 4.
