### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by zuoRambo** [yiisoft-contrib/yiiframework.com#80]
I have installed browser-sync global,but when i run `gulp build` it tips ''
```
module.js:339
    throw err;
    ^

Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rambone/PhpstormProjects/yiiframework.com/Gulpfile.js:17:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
```

**Comment by jacmoe** [comment]
Did you run this command to install it? ->
~~~
npm install -g browser-sync
~~~
You might need to prepend it with `sudo`..

**Comment by cebe** [comment]
Happened for me too, fixed it by installing without the global flag.

**Comment by jacmoe** [comment]
That works - and hopefully for the OP too - but then it will have to be installed for each project.

**Comment by zuoRambo** [comment]
@cebe me too

**Comment by jacmoe** [comment]
Good to know :)

I guess this can then be closed?
